.TH PAT 1 "2017-09-04" "Linux" "Pat Configure"
.SH NAME
pat configure \- opens pats configuration file using nano
.SH Configuration
.br
.SS Main Configuration
The default configuration file for pat is \fI~/.wl2k/config.json\fP
.br
.br
To get "on the air" you'll first have to set up your callsign, maidenhead locator, and secure login credentials. Look for the attributes \fImycall\fP, \fIlocator\fP and \fIsecure_login_password\fP and set them appropriately.
.br
{
  "mycall": "LA5NTA",
  "locator": "JP20qe",
  "secure_login_password": "MYPASSWORD",
}

