.TH PAT 1 "2017-08-15" "Linux" "Pat Overview"
.SH NAME
pat \- a cross platform Winlink client with basic messaging capabilities
.SH SYNOPSIS
\fBpat\fP [options] \fIcommand\fP [arguments]

.TP
\fIconnect\fP
Connect to a remote station.
.TP
\fIinteractive\fP
Run interactive mode.
.TP
\fIhttp\fP
Run http server for web gui.
.TP
\fIcompose\fP
Compose a new message.
.TP
\fIread\fP
Read Messages.
.TP
\fIposition\fP
Post a position report (GPSd or manual entry).
.TP
\fIextract\fP
Extract attachments from a message file.
.TP
\fIrmslist\fP
Print/search in list of RMS nodes.
.TP
\fIconfigure\fP
Open configuration file for editing.
.TP
\fIversion\fP
Print the application version.
.TP
\fIhelp\fP
Print detailed help for a given command.
